# Generated by Django 4.2.30 on 2026-08-22 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCache',
            fields=[
                ('barcode', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='条码')),
                ('name', models.CharField(max_length=128, verbose_name='商品名')),
                ('default_expiry_days', models.IntegerField(default=7, verbose_name='默认保质期天数')),
                ('category', models.CharField(choices=[('meat', '肉类'), ('vegetable', '蔬菜'), ('dairy', '乳制品'), ('seasoning', '调料'), ('snack', '零食'), ('fruit', '水果'), ('drink', '饮料'), ('other', '其他')], default='other', max_length=16, verbose_name='分类')),
                ('icon', models.CharField(blank=True, default='', max_length=32, verbose_name='图标名')),
                ('last_queried', models.DateTimeField(auto_now=True, verbose_name='最近查询时间')),
                ('query_count', models.IntegerField(default=0, verbose_name='查询次数')),
            ],
            options={
                'verbose_name': '条码缓存',
                'verbose_name_plural': '条码缓存',
            },
        ),
        migrations.CreateModel(
            name='StorageSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('zone_type', models.CharField(choices=[('cold', '冷藏'), ('frozen', '冷冻'), ('normal', '常温')], max_length=16, verbose_name='类型')),
                ('icon', models.CharField(default='box', max_length=32, verbose_name='图标名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_spaces', to='users.familygroup', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '存储空间',
                'verbose_name_plural': '存储空间',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='物品名')),
                ('category', models.CharField(choices=[('meat', '肉类'), ('vegetable', '蔬菜'), ('dairy', '乳制品'), ('seasoning', '调料'), ('snack', '零食'), ('fruit', '水果'), ('drink', '饮料'), ('other', '其他')], default='other', max_length=16, verbose_name='分类')),
                ('barcode', models.CharField(blank=True, default='', max_length=64, verbose_name='条码')),
                ('icon', models.CharField(blank=True, default='', max_length=32, verbose_name='图标名')),
                ('quantity', models.IntegerField(default=1, verbose_name='剩余数量')),
                ('unit', models.CharField(default='个', max_length=8, verbose_name='单位')),
                ('expiry_date', models.DateField(verbose_name='过期日期')),
                ('days_to_expire', models.IntegerField(help_text='录入时计算的保质期', verbose_name='保质期天数')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='是否已消耗')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消耗时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_items', to='users.user', verbose_name='录入人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='users.familygroup', verbose_name='所属家庭')),
                ('storage_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='foods.storagespace', verbose_name='存放位置')),
            ],
            options={
                'verbose_name': '食品物品',
                'verbose_name_plural': '食品物品',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('add', '新增'), ('consume', '消耗'), ('delete', '删除'), ('modify', '修改')], max_length=16, verbose_name='操作')),
                ('item_name', models.CharField(blank=True, default='', max_length=64, verbose_name='物品名称快照')),
                ('detail', models.CharField(blank=True, default='', max_length=128, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='users.familygroup', verbose_name='家庭组')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='foods.fooditem', verbose_name='操作物品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='users.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['family', 'created_at'], name='foods_opera_family__5d521e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['family', 'expiry_date'], name='foods_foodi_family__0f4987_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['family', 'storage_space'], name='foods_foodi_family__5a66e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['family', 'category'], name='foods_foodi_family__becffa_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['family', 'is_consumed'], name='foods_foodi_family__5c699e_idx'),
        ),
    ]
