# Generated by Django 4.2.30 on 2026-08-22 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=64, verbose_name='物品名')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=8, verbose_name='单位')),
                ('reason', models.CharField(choices=[('manual', '手动添加'), ('auto_predicted', '自动预测'), ('recipe_required', '菜谱所需')], default='manual', max_length=20, verbose_name='来源')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='是否已买')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='购买时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='users.user', verbose_name='创建人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='users.familygroup', verbose_name='家庭组')),
            ],
            options={
                'verbose_name': '购物清单',
                'verbose_name_plural': '购物清单',
                'ordering': ['-created_at'],
            },
        ),
    ]
